// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: kCvp2jQnHcq5LJ8txx1Rx8
// Component: jwLRJNHElz9W

import * as React from "react";

import Head from "next/head";
import Link, { LinkProps } from "next/link";
import { useRouter } from "next/router";

import {
  Flex as Flex__,
  MultiChoiceArg,
  PlasmicDataSourceContextProvider as PlasmicDataSourceContextProvider__,
  PlasmicIcon as PlasmicIcon__,
  PlasmicImg as PlasmicImg__,
  PlasmicLink as PlasmicLink__,
  PlasmicPageGuard as PlasmicPageGuard__,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  Stack as Stack__,
  StrictProps,
  Trans as Trans__,
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts,
  ensureGlobalVariants,
  generateOnMutateForSpec,
  generateStateOnChangeProp,
  generateStateOnChangePropForCodeComponents,
  generateStateValueProp,
  get as $stateGet,
  hasVariant,
  initializeCodeComponentStates,
  initializePlasmicStates,
  makeFragment,
  omit,
  pick,
  renderPlasmicSlot,
  set as $stateSet,
  useCurrentUser,
  useDollarState,
  usePlasmicTranslator,
  useTrigger,
  wrapWithClassName
} from "@plasmicapp/react-web";
import {
  DataCtxReader as DataCtxReader__,
  useDataEnv,
  useGlobalActions
} from "@plasmicapp/react-web/lib/host";

import { Reveal } from "@plasmicpkgs/react-awesome-reveal";

import { useScreenVariants as useScreenVariantswcgr3SdHclm } from "./PlasmicGlobalVariant__Screen"; // plasmic-import: _WCGR3sdHclm/globalVariant

import "@plasmicapp/react-web/lib/plasmic.css";

import projectcss from "./plasmic.module.css"; // plasmic-import: kCvp2jQnHcq5LJ8txx1Rx8/projectcss
import sty from "./PlasmicHomepage.module.css"; // plasmic-import: jwLRJNHElz9W/css

createPlasmicElementProxy;

export type PlasmicHomepage__VariantMembers = {};
export type PlasmicHomepage__VariantsArgs = {};
type VariantPropType = keyof PlasmicHomepage__VariantsArgs;
export const PlasmicHomepage__VariantProps = new Array<VariantPropType>();

export type PlasmicHomepage__ArgsType = {};
type ArgPropType = keyof PlasmicHomepage__ArgsType;
export const PlasmicHomepage__ArgProps = new Array<ArgPropType>();

export type PlasmicHomepage__OverridesType = {
  root?: Flex__<"div">;
  h1?: Flex__<"h1">;
  h3?: Flex__<"h3">;
};

export interface DefaultHomepageProps {}

const $$ = {};

function useNextRouter() {
  try {
    return useRouter();
  } catch {}
  return undefined;
}

function PlasmicHomepage__RenderFunc(props: {
  variants: PlasmicHomepage__VariantsArgs;
  args: PlasmicHomepage__ArgsType;
  overrides: PlasmicHomepage__OverridesType;
  forNode?: string;
}) {
  const { variants, overrides, forNode } = props;

  const args = React.useMemo(() => Object.assign({}, props.args), [props.args]);

  const $props = {
    ...args,
    ...variants
  };

  const __nextRouter = useNextRouter();
  const $ctx = useDataEnv?.() || {};
  const refsRef = React.useRef({});
  const $refs = refsRef.current;

  const currentUser = useCurrentUser?.() || {};

  const globalVariants = ensureGlobalVariants({
    screen: useScreenVariantswcgr3SdHclm()
  });

  return (
    <React.Fragment>
      <Head></Head>

      <style>{`
        body {
          margin: 0;
        }
      `}</style>

      <div className={projectcss.plasmic_page_wrapper}>
        <div
          data-plasmic-name={"root"}
          data-plasmic-override={overrides.root}
          data-plasmic-root={true}
          data-plasmic-for-node={forNode}
          className={classNames(
            projectcss.all,
            projectcss.root_reset,
            projectcss.plasmic_default_styles,
            projectcss.plasmic_mixins,
            projectcss.plasmic_tokens,
            sty.root
          )}
        >
          <section className={classNames(projectcss.all, sty.section__d7N70)}>
            <PlasmicImg__
              alt={""}
              className={classNames(sty.img__hRr9X)}
              displayHeight={
                hasVariant(globalVariants, "screen", "mobileOnly")
                  ? "100%"
                  : "auto"
              }
              displayMaxHeight={"none"}
              displayMaxWidth={"100%"}
              displayMinHeight={"0"}
              displayMinWidth={"0"}
              displayWidth={"100%"}
              loading={"lazy"}
              src={{
                src: "/plasmic/squirt/images/bannerEditpng.png",
                fullWidth: 1920,
                fullHeight: 1080,
                aspectRatio: undefined
              }}
            />

            <div className={classNames(projectcss.all, sty.freeBox__xNJcW)}>
              <PlasmicImg__
                alt={""}
                className={classNames(sty.img__xe6Vl)}
                displayHeight={"auto"}
                displayMaxHeight={"none"}
                displayMaxWidth={"800px"}
                displayMinHeight={"0"}
                displayMinWidth={"0"}
                displayWidth={"auto"}
                loading={"lazy"}
                src={{
                  src: "/plasmic/squirt/images/squirtieBannerLogopng.png",
                  fullWidth: 1425,
                  fullHeight: 382,
                  aspectRatio: undefined
                }}
              />

              <h1
                data-plasmic-name={"h1"}
                data-plasmic-override={overrides.h1}
                className={classNames(
                  projectcss.all,
                  projectcss.h1,
                  projectcss.__wab_text,
                  sty.h1
                )}
              >
                {"Guardian of the BASE Blockchain"}
              </h1>
            </div>
          </section>
          <section className={classNames(projectcss.all, sty.section___7Fs1A)}>
            <Stack__
              as={"div"}
              hasGap={true}
              className={classNames(projectcss.all, sty.columns__k64Zc)}
            >
              <div className={classNames(projectcss.all, sty.column__pfwj)}>
                <Reveal
                  cascade={false}
                  className={classNames("__wab_instance", sty.reveal__qfzMw)}
                  direction={"left"}
                  effect={"fade"}
                  triggerOnce={true}
                >
                  <Stack__
                    as={"div"}
                    hasGap={true}
                    className={classNames(projectcss.all, sty.freeBox__ePiPs)}
                  >
                    <PlasmicImg__
                      alt={""}
                      className={classNames(sty.img__vuG7)}
                      displayHeight={"300px"}
                      displayMaxHeight={"none"}
                      displayMaxWidth={"300px"}
                      displayMinHeight={"0"}
                      displayMinWidth={"0"}
                      displayWidth={"auto"}
                      loading={"lazy"}
                      src={{
                        src: "/plasmic/squirt/images/squirtieHatchgif.gif",
                        fullWidth: 880,
                        fullHeight: 880,
                        aspectRatio: undefined
                      }}
                    />

                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text___3ByFy
                      )}
                    >
                      {
                        "Legend has it that Squirtie was born under a brilliant star, destined for greatness from the moment he emerged from his eggshell. Raised among the gentle waves of the Cerulean Sea, Squirtie was quickly recognized for his indomitable spirit and adventurous nature."
                      }
                    </div>
                  </Stack__>
                </Reveal>
              </div>
              <div className={classNames(projectcss.all, sty.column__mAaky)}>
                <Reveal
                  className={classNames("__wab_instance", sty.reveal__v9R3V)}
                  direction={"right"}
                  triggerOnce={true}
                >
                  <Stack__
                    as={"div"}
                    hasGap={true}
                    className={classNames(projectcss.all, sty.freeBox__ewRa0)}
                  >
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__a8U70
                      )}
                    >
                      {
                        "As Squirtie grew older, he joined the notorious Squirtle Squad, a group of brave noblemons dedicated to protecting the shores of their homeland. Together, they faced countless challenges and adversaries, forging bonds of friendship that would withstand the test of time."
                      }
                    </div>
                    <PlasmicImg__
                      alt={""}
                      className={classNames(sty.img__b83Cs)}
                      displayHeight={"300px"}
                      displayMaxHeight={"none"}
                      displayMaxWidth={"300px"}
                      displayMinHeight={"0"}
                      displayMinWidth={"0"}
                      displayWidth={"auto"}
                      loading={"lazy"}
                      src={{
                        src: "/plasmic/squirt/images/squirtieSquadgif.gif",
                        fullWidth: 880,
                        fullHeight: 880,
                        aspectRatio: undefined
                      }}
                    />
                  </Stack__>
                </Reveal>
              </div>
            </Stack__>
          </section>
          <section className={classNames(projectcss.all, sty.section___8MtIi)}>
            <Stack__
              as={"div"}
              hasGap={true}
              className={classNames(projectcss.all, sty.columns__gZHnv)}
            >
              <div className={classNames(projectcss.all, sty.column__bucQ2)}>
                <Reveal
                  className={classNames("__wab_instance", sty.reveal__vgYfc)}
                  direction={"left"}
                  triggerOnce={true}
                >
                  <PlasmicImg__
                    alt={""}
                    className={classNames(sty.img__aqYbh)}
                    displayHeight={"auto"}
                    displayMaxHeight={"none"}
                    displayMaxWidth={"100%"}
                    displayMinHeight={"0"}
                    displayMinWidth={"0"}
                    displayWidth={"400px"}
                    loading={"lazy"}
                    src={{
                      src: "/plasmic/squirt/images/squirtieFarewellgif.gif",
                      fullWidth: 880,
                      fullHeight: 880,
                      aspectRatio: undefined
                    }}
                  />
                </Reveal>
              </div>
              <div className={classNames(projectcss.all, sty.column__uvTxX)}>
                <Reveal
                  cascade={false}
                  className={classNames("__wab_instance", sty.reveal__bFi46)}
                  direction={"right"}
                  effect={"fade"}
                  triggerOnce={true}
                >
                  <div
                    className={classNames(projectcss.all, sty.freeBox__iRMov)}
                  >
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__oSej5
                      )}
                    >
                      {
                        "But as the tides of destiny shifted, Squirtie felt a new calling stirring within his heart. Hearing the cries of memelovers across the Blockchain, who were falling victim to rug pulls and scams, Squirtie knew that his journey was far from over. With a heavy heart and a determined spirit, Squirtie bid farewell to his beloved Squad and set out on a new quest."
                      }
                    </div>
                  </div>
                </Reveal>
              </div>
            </Stack__>
          </section>
          <section className={classNames(projectcss.all, sty.section__nzQ3S)}>
            <Stack__
              as={"div"}
              hasGap={true}
              className={classNames(projectcss.all, sty.columns__h5Fv)}
            >
              <div className={classNames(projectcss.all, sty.column___4Mmwo)}>
                <Reveal
                  cascade={false}
                  className={classNames("__wab_instance", sty.reveal__ewAyP)}
                  direction={"left"}
                  effect={"fade"}
                  triggerOnce={true}
                >
                  <div
                    className={classNames(projectcss.all, sty.freeBox__kaQlk)}
                  >
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text___8ZCVn
                      )}
                    >
                      {
                        "Now, Squirtie roams the digital expanse of the BASE Blockchain, his shell gleaming with purpose as he seeks to lead the charge against fraud and deception. With every scam uncovered and every rug pull thwarted, Squirtie restores a glimmer of hope to memelovers seeking to ride the waves of real gains. Join us on this noble quest as Squirtie stands as the Guardian of the BASE Blockchain, championing honesty and fair play for all!"
                      }
                    </div>
                  </div>
                </Reveal>
              </div>
              <div className={classNames(projectcss.all, sty.column__hqjSj)}>
                <Reveal
                  className={classNames("__wab_instance", sty.reveal__ypEKd)}
                  direction={"right"}
                  triggerOnce={true}
                >
                  <PlasmicImg__
                    alt={""}
                    className={classNames(sty.img__s9ETr)}
                    displayHeight={"auto"}
                    displayMaxHeight={"none"}
                    displayMaxWidth={"100%"}
                    displayMinHeight={"0"}
                    displayMinWidth={"0"}
                    displayWidth={"auto"}
                    loading={"lazy"}
                    src={{
                      src: "/plasmic/squirt/images/squirtieSurfgif.gif",
                      fullWidth: 880,
                      fullHeight: 880,
                      aspectRatio: undefined
                    }}
                  />
                </Reveal>
              </div>
            </Stack__>
          </section>
          <section className={classNames(projectcss.all, sty.section___0Nf4X)}>
            <div className={classNames(projectcss.all, sty.columns__mrR6Q)}>
              <div className={classNames(projectcss.all, sty.column__qAb7Z)}>
                <PlasmicImg__
                  alt={""}
                  className={classNames(sty.img__rcoW9)}
                  displayHeight={"400px"}
                  displayMaxHeight={"none"}
                  displayMaxWidth={"100%"}
                  displayMinHeight={"0"}
                  displayMinWidth={"0"}
                  displayWidth={"400px"}
                  loading={"lazy"}
                  src={{
                    src: "/plasmic/squirt/images/squirtieCoinpng.png",
                    fullWidth: 960,
                    fullHeight: 960,
                    aspectRatio: undefined
                  }}
                />
              </div>
              <div className={classNames(projectcss.all, sty.column__shN8Y)}>
                <h3
                  data-plasmic-name={"h3"}
                  data-plasmic-override={overrides.h3}
                  className={classNames(
                    projectcss.all,
                    projectcss.h3,
                    projectcss.__wab_text,
                    sty.h3
                  )}
                >
                  {
                    "-Tokenomics: 1,000,000,000 0% Tax. \n45% LP\n45% Airdrop \n10% Marketing/KOL/CEX \n-Socials: @squirtiebase \n-Roadmap (maybe make a land)\n\nPresale \nLaunch\nCEX\nMarketing \n\nPhase 2: \nTOP HOLDERS will be air dropped a Squirtie EGG NFT\n"
                  }
                </h3>
              </div>
            </div>
          </section>
        </div>
      </div>
    </React.Fragment>
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  root: ["root", "h1", "h3"],
  h1: ["h1"],
  h3: ["h3"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  (typeof PlasmicDescendants)[T][number];
type NodeDefaultElementType = {
  root: "div";
  h1: "h1";
  h3: "h3";
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicHomepage__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicHomepage__VariantsArgs;
    args?: PlasmicHomepage__ArgsType;
    overrides?: NodeOverridesType<T>;
  } & Omit<PlasmicHomepage__VariantsArgs, ReservedPropsType> & // Specify variants directly as props
    /* Specify args directly as props*/ Omit<
      PlasmicHomepage__ArgsType,
      ReservedPropsType
    > &
    /* Specify overrides for each element directly as props*/ Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    /* Specify props for the root element*/ Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: PlasmicDescendants[nodeName],
          internalArgPropNames: PlasmicHomepage__ArgProps,
          internalVariantPropNames: PlasmicHomepage__VariantProps
        }),
      [props, nodeName]
    );
    return PlasmicHomepage__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicHomepage";
  } else {
    func.displayName = `PlasmicHomepage.${nodeName}`;
  }
  return func;
}

export const PlasmicHomepage = Object.assign(
  // Top-level PlasmicHomepage renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    h1: makeNodeComponent("h1"),
    h3: makeNodeComponent("h3"),

    // Metadata about props expected for PlasmicHomepage
    internalVariantProps: PlasmicHomepage__VariantProps,
    internalArgProps: PlasmicHomepage__ArgProps,

    // Page metadata
    pageMetadata: {
      title: "",
      description: "",
      ogImageSrc: "",
      canonical: ""
    }
  }
);

export default PlasmicHomepage;
/* prettier-ignore-end */
